# Generated by Django 4.2.4 on 2023-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_property_image_property_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
    ]
