# Generated by Django 4.2.4 on 2023-09-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
