# Generated by Django 4.2.4 on 2023-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_property_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default='asda', unique=True),
            preserve_default=False,
        ),
    ]
