# Generated by Django 4.2.4 on 2023-10-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_land',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
