# Generated by Django 4.2.4 on 2023-09-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastName',
        ),
    ]
