# Generated by Django 4.2.4 on 2023-11-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_property_is_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reception',
            field=models.IntegerField(null=True),
        ),
    ]
