# Generated by Django 4.2.4 on 2023-12-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_property_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_land',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearest_station',
            field=models.JSONField(null=True),
        ),
    ]
